# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if available
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift package
custom: ['https://voice.varco.ai', 'https://nc-ai.com/ko']
